name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
    volumes:
      - /home/ubuntu/hyperliquid/hl-data:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /home/ubuntu/hyperliquid/hl-data:/home/hluser/hl/data


volumes:
  hl-data:
    driver: local
